<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Beds</name>
   <tag></tag>
   <elementGuidId>02d46c82-9a0d-4532-8008-0f7dd4dd6a5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-bar']/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>630838ef-ada4-43be-bda2-915bfcd2e4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Beds
        </value>
      <webElementGuid>0781cd29-29c3-4e43-a37c-ba8a761698df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-bar&quot;)/div[@class=&quot;search-bar&quot;]/div[@class=&quot;search-menu&quot;]/div[@class=&quot;search-menu__item&quot;]/a[1]</value>
      <webElementGuid>51e5cb8d-3c6f-4f7a-aad3-484830867d44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-bar']/div/div/div[2]/a</value>
      <webElementGuid>5e43275a-16a4-4188-be5d-8782d2cd95be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Beds')]</value>
      <webElementGuid>ce5461af-e1c2-4d5b-b737-efbad8f73a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Up to K20K Lakhs'])[1]/following::a[1]</value>
      <webElementGuid>3780bc4f-4951-4bc7-a02d-a5ed0a73eaba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advice'])[2]/following::a[2]</value>
      <webElementGuid>4f9ac2b0-d872-4f7b-bda4-41319572efe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Property Type'])[1]/preceding::a[1]</value>
      <webElementGuid>69ff4a70-e463-43c9-8bd2-b401295d31c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Features'])[1]/preceding::a[2]</value>
      <webElementGuid>3fdee0ad-b971-46a2-86ef-d0f9dee23722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beds']/parent::*</value>
      <webElementGuid>ece4d150-2e98-4a0b-9ef9-06b649ac55c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/a</value>
      <webElementGuid>ee5b729c-a003-40f6-af87-bc2e66957e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '
        Beds
        ' or . = '
        Beds
        ')]</value>
      <webElementGuid>b4de9c80-db01-41be-8a53-caf929be0f23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
