<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Nong Suea_link-unit</name>
   <tag></tag>
   <elementGuidId>3f5cd1c4-a367-4db3-97a8-d25878e4c5d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-result']/div[5]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.link-unit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ad066e56-b289-4a69-b344-240c6382d434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-unit</value>
      <webElementGuid>e33615ed-9c05-40f2-9fbe-93d94ee55cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.fazwaz.com/property-sales/3-bedroom-house-for-sale-at-baanfah-piyarom-tendro-wongwaen-lumlukka-klong-6-in-bueng-kham-phroi-pathum-thani-u1761316</value>
      <webElementGuid>e0e45a8c-a45b-4d78-b9e2-cde36d695beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>6749f0b2-ed73-413f-a9ac-289bd4fff6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-result&quot;)/div[@class=&quot;result-search__row units_loading_wrapper&quot;]/div[@class=&quot;loaded&quot;]/div[@class=&quot;result-search__item&quot;]/a[@class=&quot;link-unit&quot;]</value>
      <webElementGuid>b660d29b-8ca5-490c-8d77-ef60d9dc9775</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-result']/div[5]/div/div/a</value>
      <webElementGuid>32baf5ca-88bb-4379-a740-438c6eb8859e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nong Suea'])[1]/following::a[1]</value>
      <webElementGuid>d058d9f8-8a5b-4d41-a844-2acb1e78dea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sam Khok'])[1]/following::a[2]</value>
      <webElementGuid>b2e454fa-6af9-4e5e-939e-5d950c91403f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See All'])[1]/preceding::a[1]</value>
      <webElementGuid>8e0f5a35-8d0e-4925-8a69-89b0233dac5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baanfah Piyarom Tendro Wongwaen-Lumlukka Klong 6'])[1]/preceding::a[1]</value>
      <webElementGuid>9793db59-d7c0-4d71-acef-4c9d4b234d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.fazwaz.com/property-sales/3-bedroom-house-for-sale-at-baanfah-piyarom-tendro-wongwaen-lumlukka-klong-6-in-bueng-kham-phroi-pathum-thani-u1761316')]</value>
      <webElementGuid>a6e12171-b505-4623-919b-8708e89301f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/a</value>
      <webElementGuid>1e3aba45-1477-4fba-9bb0-63544deb45ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.fazwaz.com/property-sales/3-bedroom-house-for-sale-at-baanfah-piyarom-tendro-wongwaen-lumlukka-klong-6-in-bueng-kham-phroi-pathum-thani-u1761316']</value>
      <webElementGuid>7190ef70-6e10-40ec-aed6-108aa494054c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baan Eua Arthorn Rangsit Klong 10/2'])[1]/preceding::a[1]</value>
      <webElementGuid>b5327a8d-a16b-49e5-8ead-4b7a9ccd0738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.fazwaz.com/property-sales/2-bedroom-house-for-sale-at-baan-eua-arthorn-rangsit-klong-102-in-bueng-sanan-pathum-thani-u1720192')]</value>
      <webElementGuid>57e8ab07-f0ea-497f-a6c8-6c4419508d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.fazwaz.com/property-sales/2-bedroom-house-for-sale-at-baan-eua-arthorn-rangsit-klong-102-in-bueng-sanan-pathum-thani-u1720192']</value>
      <webElementGuid>91334e46-ac55-4e32-b730-cb039bfc6139</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
