<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Private Garden</name>
   <tag></tag>
   <elementGuidId>0db50613-b7aa-45f6-bff1-4b723ef7a8a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>13e15198-433e-43cf-8acb-99b9edda80b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86f0fc03-2512-4b17-8a80-55914b94d2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>87e6319c-a8f6-4e69-8000-faa33adc391e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>cdd83e8b-7552-4ccb-8952-ca91ee8b73e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Private Garden
                    </value>
      <webElementGuid>7d624be2-831c-4de9-bde6-71e3142505e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9&quot;)</value>
      <webElementGuid>1d6b4bda-ee4c-4464-89f5-7384f2038773</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='9']</value>
      <webElementGuid>393229fb-0f08-4516-bbce-52fcc99da260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-bar']/div/div/div[4]/div/div/div[2]/div/div/button[5]</value>
      <webElementGuid>489a298e-eadc-40be-8c30-d3a8a6fda320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sauna'])[1]/following::button[1]</value>
      <webElementGuid>42046e0a-db46-4488-9f6a-7b85b9650d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jacuzzi'])[1]/following::button[2]</value>
      <webElementGuid>c9021313-1606-449f-a19d-c359c27bf421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private Gym'])[1]/preceding::button[1]</value>
      <webElementGuid>8961fc33-95bb-41c9-8a9a-50a1a1fae830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duplex'])[1]/preceding::button[2]</value>
      <webElementGuid>097074c4-8c1c-46e9-93b3-e28548ad741e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Private Garden']/parent::*</value>
      <webElementGuid>7170abe3-ca23-499e-a09f-a0c549f80817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button[5]</value>
      <webElementGuid>5d0404ee-65d1-4cc1-a48b-c6915dff0fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '9' and (text() = '
                        Private Garden
                    ' or . = '
                        Private Garden
                    ')]</value>
      <webElementGuid>34addd40-e3ce-433d-bb60-455122387fec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
