<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_K20,000 Lakhs</name>
   <tag></tag>
   <elementGuidId>2290c509-742e-4cf2-a262-164a48258e24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@value='20000']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li[value=&quot;20000&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5c5c40ae-8eff-4f35-827d-42480de7764a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>20000</value>
      <webElementGuid>9737f1bd-0340-426a-bfd3-0037b3151ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>K20,000 Lakhs</value>
      <webElementGuid>f4c20a96-6762-4557-91c2-15acc96b410b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-bar&quot;)/div[@class=&quot;search-bar&quot;]/div[@class=&quot;search-menu&quot;]/div[@class=&quot;search-menu__item&quot;]/div[@class=&quot;wrap_range_price&quot;]/div[@class=&quot;select-mobile&quot;]/ul[@class=&quot;order-options&quot;]/li[12]</value>
      <webElementGuid>20a61ffe-e1eb-48ed-87a8-140233a3dd4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@value='20000']</value>
      <webElementGuid>eb4beb08-7a4c-414e-9866-d01d44235155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-bar']/div/div/div/div/div[2]/ul/li[12]</value>
      <webElementGuid>5c059e97-1e10-4de3-a5cb-cb9a3d299aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K10,000 Lakhs'])[1]/following::li[1]</value>
      <webElementGuid>857bc9f6-f0d0-426d-b7f3-d321eb532e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K6,000 Lakhs'])[1]/following::li[2]</value>
      <webElementGuid>3b572887-1e61-4839-a9a1-d9d2b0f1f34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any Price'])[2]/preceding::li[1]</value>
      <webElementGuid>69167b41-cbfc-4c9a-be1f-c11cec045c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beds'])[1]/preceding::li[2]</value>
      <webElementGuid>f6a29ad4-3bf2-41a0-bb36-15394ba85877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='K20,000 Lakhs']/parent::*</value>
      <webElementGuid>2419dd97-504d-4981-9307-a78062c2cb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[12]</value>
      <webElementGuid>b0f1dc87-5d51-478c-b641-a7b635298b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'K20,000 Lakhs' or . = 'K20,000 Lakhs')]</value>
      <webElementGuid>1301cb4a-1016-4f6d-8afe-dfa689ce1440</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
