<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Completed</name>
   <tag></tag>
   <elementGuidId>1c8cb3b8-bac8-47c9-8dd7-0d9f399745d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>18b3a287-ec25-4a24-a080-79059d79e7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1dc06c2b-ce05-4ba3-8eab-76a425b370a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_item</value>
      <webElementGuid>935f755f-b9c0-4024-81d9-56039744131b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Completed
                    </value>
      <webElementGuid>21435e6e-36ee-41b2-86ce-f1a96de914d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2&quot;)</value>
      <webElementGuid>7dafb4eb-ccde-42cc-9037-8488639381f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='2']</value>
      <webElementGuid>e69fddeb-04c9-49ea-9d50-0d4bafec0fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-bar']/div/div/div[5]/div/div/div[4]/div/div/span[2]</value>
      <webElementGuid>5105c5a0-2150-49a2-9b77-0d69621a75e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Off Plan'])[1]/following::span[1]</value>
      <webElementGuid>80cd56c8-5a18-48c7-b39e-05c7d6207e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completion Status'])[1]/following::span[2]</value>
      <webElementGuid>a552c097-5bb8-41e8-bbd6-cb056e571502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Tour'])[1]/preceding::span[1]</value>
      <webElementGuid>80663ce7-3c74-4f0f-8383-30b69b95e663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only Show Homes with video Tours'])[1]/preceding::span[1]</value>
      <webElementGuid>70d78772-b6b7-475e-b4b9-ed972074c242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Completed']/parent::*</value>
      <webElementGuid>dbce5d3d-2001-4d6e-a56d-94e9e60b386b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span[2]</value>
      <webElementGuid>07ab7c89-e6aa-4ad7-a74a-097f40072b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '2' and (text() = '
                        Completed
                    ' or . = '
                        Completed
                    ')]</value>
      <webElementGuid>8c1d773d-d11a-4bdb-b727-605c739149c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
