<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MMK - Kyats (Lakh)_auto-complete-sear_800c28</name>
   <tag></tag>
   <elementGuidId>b3677a29-b53f-42e1-acfa-cbe82cc96b7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-box-mobile']/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.auto-complete-search-input__input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>342b3846-7e00-469d-a714-d35ab0adf38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by location, station, project or unit ID</value>
      <webElementGuid>ddd38c93-12ce-4293-b3ed-f648d62dd872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0a734939-759e-4bec-8543-c146dd1f9d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>search-input</value>
      <webElementGuid>7a980b36-2b67-415c-b859-220df1939ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cypress</name>
      <type>Main</type>
      <value>home-search-input-auto-complete</value>
      <webElementGuid>016081f5-2937-4d2c-ad3b-d9d92a95cbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auto-complete-search-input__input</value>
      <webElementGuid>7d100a0f-a543-4946-af10-b7790304810d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-box-mobile&quot;)/div[@class=&quot;auto-complete-search-input is-focus&quot;]/div[@class=&quot;inner-input&quot;]/input[@class=&quot;auto-complete-search-input__input&quot;]</value>
      <webElementGuid>8a4b977f-5d0c-4ebc-a556-aa3fc09404e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-box-mobile']/div/div/input</value>
      <webElementGuid>214d3871-015a-4189-9a30-42dc4fb46fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>31dc5e5d-2baf-45ba-ae75-1b6bea62bbd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search by location, station, project or unit ID']</value>
      <webElementGuid>be961b7b-8faa-4515-ab4a-f986c080bbad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
